module_name: redmine_license_manager
naming_prefix: rlm
# values that need to be created within a given submodule of the setup class
# See locales file for the name of the created instance
modules:
  setup:
    # Locales are used to setup the names of the given instances
    # Rake task can be used to change the names of the listed entries
    # `identify_column` is used as the unique key
    # `entries` are the values created - mapped to the `identify_column` attribute via the Setup.name (will be prefixed with 'naming_prefix')
    #
    activities:
      class_name: TimeEntryActivity
      entries: [license, maintainance]

    trackers:
      class_name: Tracker
      entries: [license, license_extension]
      additional_attributes:
        default_status_id: 'RLM::Setup::IssueStatuses.license_inactive.id'
        # This will run through eval(), Special case, as Trackers need a value for default status id even though using eval isn't pretty nice coding style.
        # Improvements welcome

    issue_statuses:
      class_name: IssueStatus
      entries: [license_active, license_ordered, license_inactive]

    issue_custom_fields:
      class_name: IssueCustomField
      entries:
        - license_price
        - license_purchase_price
        - maintainance_price
        - maintainance_purchase_price
        - maintainance_date
        - maintainance_paid_until
        - maintainance_invoice_received
        - maintainance_period
        - customer_project_reference
        - customer_invoice_reference
        - license_product_name
        - license_count
        - serialnumber
        - controlnumber
        - license_lef
        
      # special case here, as the entries dont just have a name, they also have a field type and other settings
      entry_settings:
        license_price:
          field_format: float
          is_required: true
        license_purchase_price:
          field_format: float
          is_required: true
        maintainance_price:
          field_format: float
        maintainance_purchase_price:
          field_format: float
        maintainance_date:
          field_format: date
        maintainance_paid_until:
          field_format: date
        maintainance_invoice_received:
          field_format: bool
        maintainance_period:
          field_format: int
        customer_project_reference:
          field_format: int
        customer_invoice_reference:
          field_format: string
          editable: true  
        license_product_name:
          field_format: list
          possible_values: '-'
        license_count:
          field_format: int
        serialnumber:
          field_format: string
        controlnumber:
          field_format: string      
        license_lef:
          field_format: text
    
    time_entry_custom_fields:
      class_name: TimeEntryCustomField
      entries:
        - amount
        - customer_invoice_reference
        
      entry_settings:
        amount:
          field_format: float
        customer_invoice_reference:
          field_format: string
